export const GET_MOVIES_ATTEMPING = "GET_MOVIES_ATTEMPING";
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";

export const GET_GENRES_ATTEMPING = "GET_GENRES_ATTEMPING";
export const GET_GENRES_FAILED = "GET_GENRES_FAILED";
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";

export const GET_MOVIE_CREDITS_ATTEMPING = "GET_MOVIE_CREDITS_ATTEMPING";
export const GET_MOVIE_CREDITS_FAILED = "GET_MOVIE_CREDITS_FAILED";
export const GET_MOVIE_CREDITS_SUCCESS = "GET_MOVIE_CREDITS_SUCCESS";
